- hosts: all
  gather_facts: no
  tasks:
  - name: Set password if expired
    delegate_to: 127.0.0.1
    become: no
    expect:
      command: ssh -o "StrictHostKeyChecking=no" rhnadmin@{{ inventory_hostname }}
      timeout: 5
      responses:
        "password:":
          - "Nov$2020r3dha5#10"
          - "Nov$2020r3dha5#10"
          - "Sep$2020r3dha5#09"
          - "Sep$2020r3dha5#09"
        # if succesfully login then quit
        "\\~\\]\\$": exit
    register: status
    changed_when: "'authentication tokens updated successfully' in status.stdout"

  - debug: var=status
