- name: configure NTP Server  
  hosts: all
  vars:
    ntpserver1: "10.96.4.65" 
  tasks:
  - name: set timezone
    shell: timedatectl set-timezone Asia/Kolkata

  - name: Install NTP
    yum: name=ntp state=installed 
    tags: ntp
 
  - name: Copy over the NTP configuration
    template: src=ntp.conf dest=/etc/ntp.conf
    notify:
    - restart ntpd
    tags: ntp
 
  - name: Make sure NTP is stopped
    service: name=ntpd state=stopped enabled=yes
    tags: ntp
 
  - name: Sync time initialy
    shell: ntpdate "{{ ntpserver1 }}"
    tags: ntp
    ignore_errors: yes

  - name: Make sure NTP is started up
    service: name=ntpd state=started enabled=yes
    tags: ntp

  - name: Sync hwclock
    shell: hwclock -w
    tags: ntp

  handlers:
  - name: restart ntpd
    service: name=ntpd state=restarted
